version: '3'

services:
  postgres:
    image: kartoza/postgis:13.0
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_CARTO_DB}
      POSTGRES_MULTIPLE_EXTENSIONS: ${POSTGRES_EXTENSIONS}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT:-8080}:80
    volumes:
      - ./pgadmin:/root/.pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin:
